# glpi-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glpi-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/glpi

