# glpi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
        - name: glpi
          image: diouxx/glpi:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: glpi-data
              mountPath: /var/www/html
      volumes:
        - name: glpi-data
          persistentVolumeClaim:
            claimName: glpi-pvc

