apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projet-cicd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moyoboza/projet_CI_CD.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

